# 共用替換變數（Trigger 可覆寫）
substitutions:
  _REGION: asia-east1
  _AR_REPO: demo-images
  _IMAGE_NAME: unixtime-api      # （Trigger 會覆寫）
  _CONTEXT: unixtime-api         # （Trigger 會覆寫）
  _DOCKERFILE: ${_CONTEXT}/Dockerfile
  _TAG: "sha-${SHORT_SHA}"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
# Step 1: Build the container image
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - -f
    - ${_DOCKERFILE}
    - -t
    - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:${_TAG}
    - ${_CONTEXT}

# Step 2: Push the container image to Artifact Registry
- name: gcr.io/cloud-builders/docker
  args: ["push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:${_TAG}"]

# Step 3: Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - run
    - deploy
    - ${_IMAGE_NAME}
    - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:${_TAG}
    - --region=${_REGION}
    - --platform=managed
    - --allow-unauthenticated
    - --port=8080


images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:${_TAG}